from pathlib import Path
import re

main_path = Path('lib/main.dart')
pubspec_path = Path('pubspec.yaml')
text = main_path.read_text(encoding='utf-8')
pubspec = pubspec_path.read_text(encoding='utf-8')


def remove_one_class(source: str, class_name: str) -> str:
    marker = f'class {class_name}'
    start = source.find(marker)
    if start < 0:
        raise SystemExit(f'cleanup class not found: {class_name}')
    next_class = re.search(r'^class\s+', source[start + len(marker):], flags=re.M)
    if next_class is None:
        raise SystemExit(f'next class not found after: {class_name}')
    end = start + len(marker) + next_class.start()
    return source[:start] + source[end:]


def replace_required(old: str, new: str, label: str) -> None:
    global text
    if old not in text:
        raise SystemExit(f'{label} not found')
    text = text.replace(old, new, 1)


# Remove only obsolete presentation/helper classes. Broad range deletion is
# unsafe because later scripts insert active challenges and agreements nearby.
for class_name in [
    '_JourneySteps extends StatelessWidget',
    '_JourneyStep extends StatelessWidget',
    '_DottedConnector extends StatelessWidget',
    '_AttentionCard extends StatelessWidget',
    '_ResearchNote extends StatelessWidget',
    '_SupportChoiceGrid extends StatelessWidget',
    '_ActionCenterCard extends StatelessWidget',
    '_OnboardingSupportCard extends StatelessWidget',
    '_QuietStatement extends StatelessWidget',
    '_DigitalActionAssistantCard extends StatelessWidget',
    '_AssistantSuggestion extends StatelessWidget',
]:
    text = remove_one_class(text, class_name)


# Remove every known live route to the postponed digital assistant. Some of
# these may already be removed by rewrite_v0132_product_polish.py, so the edits
# are idempotent and the strict source assertions below are authoritative.
for block in [
    r'''              SupportTile(
                type: Support.ai,
                selected: support == Support.ai,
                onTap: () => setState(() => chosen = Support.ai),
              ),
''',
    r'''          _SupportButton(
            icon: Icons.auto_awesome_rounded,
            label: 'С цифровым помощником',
            onPressed: () => _open(context, Support.ai),
          ),
          const SizedBox(height: 8),
''',
    r'''          _SimpleSupportCard(
            type: Support.ai,
            onPressed: () => Navigator.push(
              context,
              MaterialPageRoute(
                builder: (_) => ActionEditor(
                  app: app,
                  goalDefault: app.goal != null,
                  initialSupport: Support.ai,
                ),
              ),
            ),
          ),
''',
]:
    if block in text:
        text = text.replace(block, '', 1)

# Correct the previously over-escaped enum-picker filter.
text = re.sub(
    r'Support\.values\s*\.map\(',
    'Support.values.where((value) => value != Support.ai).map(',
    text,
)
text = text.replace(
    'widget.app.setSupport(widget.item, Support.ai);',
    'widget.app.setSupport(widget.item, Support.solo);',
)

# The local decomposition logic can remain, but it must never classify the
# action as digital-assistant support or show that label in a green banner.
support_logic_start = text.index('class SupportLogic {')
support_logic_end = text.index(
    '  static List<String> steps(String task) {',
    support_logic_start,
)
support_logic = text[support_logic_start:support_logic_end]
support_logic = support_logic.replace('Support.ai,', 'Support.solo,')
support_logic = support_logic.replace(
    'Цифровой помощник предложит один понятный первый шаг.',
    'Приложение поможет определить один понятный первый шаг.',
)
text = text[:support_logic_start] + support_logic + text[support_logic_end:]

# Normalize all remaining visible names, including formatting variants in
# switch expressions generated by earlier release scripts.
text = text.replace(
    "Support.ai => 'С цифровым помощником'",
    "Support.ai => 'Самостоятельно'",
)

# Old saved actions with support=ai must load as independent work. This fixes
# the banner for users who already tapped the old option in a previous build.
replace_required(
    r'''      support: Support.values.firstWhere(
        (e) => e.name == j['support'],
        orElse: () => Support.solo,
      ),''',
    r'''      support: j['support'] == Support.ai.name
          ? Support.solo
          : Support.values.firstWhere(
              (e) => e.name == j['support'],
              orElse: () => Support.solo,
            ),''',
    'ActionItem legacy support parser',
)

# Editing from "Путь к цели" returns one route back instead of clearing the
# whole stack to the root "Сегодня" tab.
replace_required(
    r'''    if (scheduleAction) {
      await NotificationService.instance.schedule(action);
      if (!mounted) return;
      Navigator.popUntil(context, (route) => route.isFirst);
      return;
    }''',
    r'''    if (scheduleAction) {
      await NotificationService.instance.schedule(action);
      if (!mounted) return;
      if (existing != null) {
        Navigator.pop(context);
      } else {
        Navigator.popUntil(context, (route) => route.isFirst);
      }
      return;
    }''',
    'scheduled action return block',
)
replace_required(
    r'''    if (existing != null || !useTimer) {
      Navigator.popUntil(context, (route) => route.isFirst);
      return;
    }''',
    r'''    if (existing != null) {
      Navigator.pop(context);
      return;
    }

    if (!useTimer) {
      Navigator.popUntil(context, (route) => route.isFirst);
      return;
    }''',
    'editing action return block',
)


# Source-level regression gates for all three reported symptoms.
for forbidden in [
    "label: 'С цифровым помощником'",
    'type: Support.ai,',
    'initialSupport: Support.ai',
    'chosen = Support.ai',
    '_open(context, Support.ai)',
    'widget.app.setSupport(widget.item, Support.ai)',
    "Support.ai => 'С цифровым помощником'",
]:
    if forbidden in text:
        raise SystemExit(f'hidden assistant path remains: {forbidden}')

if re.search(r'Support\.values\s*\.map\(', text):
    raise SystemExit('unfiltered Support.values picker remains')
if 'Support.ai,' in text[support_logic_start:support_logic_end]:
    raise SystemExit('SupportLogic still recommends the hidden assistant')
if 'j[\'support\'] == Support.ai.name' not in text:
    raise SystemExit('legacy Support.ai migration is missing')
if 'if (existing != null) {\n      Navigator.pop(context);' not in text:
    raise SystemExit('goal-path return fix is missing')

if 'version: 0.13.2+31' not in pubspec:
    raise SystemExit('Expected v0.13.2+31 version not found')
pubspec = pubspec.replace('version: 0.13.2+31', 'version: 0.13.2+32', 1)

main_path.write_text(text, encoding='utf-8')
pubspec_path.write_text(pubspec, encoding='utf-8')
print('Removed all assistant routes, migrated legacy values and preserved goal navigation')
